### ISSUE TITLE
Manifest V3

### ISSUE THREAD

**Issue by setebe** [eric60/YouTube-Blocker#7]
Is there any chance to convert this extension to manifest V3?

**Comment by eric60** [comment]
Thanks for bringing this up. 
I think I can finish it around April/May before the June deadline, I still use this so will definitely look into it.

> For extensions publishers who still publish Manifest V2 extensions, we highly recommend completing migration to Manifest V3 before June 2024. We've published a migration guide covering everything you need to know to successfully migrate.Nov 16, 2023
https://developer.chrome.com/blog/resuming-the-transition-to-mv3#:~:text=For%20extensions%20publishers%20who%20still,to%20know%20to%20successfully%20migrate.

**Comment by eric60** [comment]
resolved with PR https://github.com/eric60/YouTube-Blocker/pull/8
